/**
 * SPEC-207 Test Design tracer bullet (Phase 3,
 * docs/proposals/professional-qa-mcp-roadmap.md). Deterministic only — no
 * Reasoning Provider — per ADR-002 (rule engine before LLM): a criterion
 * this module cannot bind to a discovered Semantic UI element (this
 * roadmap's Phase 1) becomes a `TestCaseGenerationFinding`, never a
 * fabricated step or assertion (SPEC-207 §6). Generated steps use Phase 2's
 * semantic interaction vocabulary (accessible name/role), so a generated
 * `TestCase` can be handed straight to `ExecuteBrowserTest` without a human
 * hand-authoring a `PlaywrightExecutionPlan`.
 *
 * Per SPEC-207 §4/§3 ("normal, alternate, boundary, and failure behavior
 * SHALL be considered"), a bindable, expected_text-bearing criterion
 * produces up to four `TestCaseVariant`s per editable field, not just the
 * one happy-path case: positive, negative, boundary, adversarial. Every
 * probe value below is a fixed, benign, non-destructive literal — none of
 * it is an attempt at a real exploit, and none of it is generated by a
 * Reasoning Provider (ADR-002).
 */
import type {
  WorkspaceAuthorizer,
} from "../requirement-review/public.js";
import { readString } from "../shared/rule-engine-support.js";
import type {
  GenerateTestCasesResult,
  TestCase,
  TestCaseExpectedResult,
  TestCaseGeneratedAssertion,
  TestCaseGenerationFinding,
  TestCaseGenerationRequest,
  TestCaseGenerationUiElement,
  TestCaseStep,
  TestCaseVariant,
} from "./public.js";

export interface IdFactory {
  next(scope: "test-case" | "finding"): string;
}

type Dependencies = Readonly<{
  authorizer: WorkspaceAuthorizer;
  ids: IdFactory;
}>;

/**
 * Fixed, benign probe values (SPEC-207 §4 error guessing/boundary
 * analysis). `adversarial` strings are standard input-validation probes —
 * inert unless the application fails to escape output, which is exactly
 * the bug this variant checks for. No payload here is destructive, carries
 * a callback, or attempts code execution beyond a harmless `alert(1)`
 * marker a correctly-escaping page will never run.
 *
 * `<img src=x onerror=alert(1)>` is used rather than `<script>alert(1)</script>`
 * because the DOM spec deliberately never executes a `<script>` tag
 * inserted via `innerHTML` (in any browser) — using it as the probe would
 * make this variant unable to ever catch a real `innerHTML`-based XSS bug,
 * silently passing every vulnerable page. `onerror` on a broken image *does*
 * fire through `innerHTML`, which is why it is the standard XSS test vector
 * for exactly this class of bug.
 */
const BOUNDARY_VALUE = "x".repeat(300);
const ADVERSARIAL_VALUES: readonly string[] = ["<img src=x onerror=alert(1)>", "' OR '1'='1"];
const SYSTEM_ERROR_MARKERS: readonly string[] = ["stack trace", "exception", "internal server error", "traceback"];

/** Deep module: one `generate()` call hides authorization, per-criterion binding, variant expansion, and TestCase assembly. */
export class GenerateTestCases {
  readonly #dependencies: Dependencies;

  constructor(dependencies: Dependencies) {
    this.#dependencies = dependencies;
  }

  async generate(request: TestCaseGenerationRequest): Promise<GenerateTestCasesResult> {
    const authorization = await this.#dependencies.authorizer.authorize({
      operation_id: request.operation_id,
      context: request.context,
      purpose: "generate test cases",
      consequence_class: "advisory",
      // Only `test-case:create` — this Skill receives acceptance criteria
      // as already-resolved input (either from a governed Requirement or
      // inline caller intent); it never reads a Requirement itself, so it
      // has no business requiring `requirement:read` (that permission, if
      // needed, is the caller/executor's concern before this Skill runs).
      required_permissions: ["test-case:create"],
      resource_refs: [`workspace:${request.workspace_id}`, request.requirement_ref],
    });
    if (!authorization.ok) {
      return {
        ok: false,
        failure: {
          class: "authorization",
          code: authorization.failure.code,
          message: authorization.failure.message,
          retryable: authorization.failure.retryable,
          evidence: [...authorization.failure.evidence],
        },
      };
    }

    if (request.acceptance_criteria.length === 0) {
      return {
        ok: true,
        value: {
          schema_version: "1.0.0",
          workspace_id: request.workspace_id,
          requirement_ref: request.requirement_ref,
          test_cases: [],
          findings: [
            {
              id: this.#dependencies.ids.next("finding"),
              category: "no_acceptance_criteria",
              message: "The requirement has no acceptance criteria to generate test cases from.",
              evidence: [request.requirement_ref],
            },
          ],
          generated_assertions: [],
        },
      };
    }

    const fields = request.ui_map_elements.filter((element) => element.kind === "field");
    const actions = request.ui_map_elements.filter((element) => element.kind === "action");

    const testCases: TestCase[] = [];
    const findings: TestCaseGenerationFinding[] = [];
    const generatedAssertions: TestCaseGeneratedAssertion[] = [];

    for (const criterion of request.acceptance_criteria) {
      const criterionId = readString(criterion, "id") ?? "unknown-criterion";
      const statement = readString(criterion, "statement");
      if (statement === undefined) {
        findings.push({
          id: this.#dependencies.ids.next("finding"),
          category: "unbindable_criterion",
          message: `Acceptance criterion "${criterionId}" has no statement text to bind against the discovered UI.`,
          evidence: [`${request.requirement_ref}#${criterionId}`],
        });
        continue;
      }

      const matchedAction = actions.find((element) => statementMentionsName(statement, element.accessible_name));
      const matchedFields = fields.filter((element) => statementMentionsName(statement, element.accessible_name));

      if (matchedAction === undefined && matchedFields.length === 0) {
        findings.push({
          id: this.#dependencies.ids.next("finding"),
          category: "unbindable_criterion",
          message: `No discovered UI element (field or action) matches acceptance criterion "${criterionId}": "${statement}". A test case was not fabricated.`,
          evidence: [`${request.requirement_ref}#${criterionId}`, `ui-map:${request.ui_map_source_url}`],
        });
        continue;
      }

      const editableFields = matchedFields.filter((field) => field.interaction_hint === "editable");
      const expectedText = readString(criterion, "expected_text");

      const positive = this.#buildCase({
        request,
        criterionId,
        variant: "positive",
        matchedFields,
        matchedAction,
        fieldValues: undefined,
        expectedText,
        variantField: undefined,
      });
      testCases.push(positive.testCase);
      if (positive.assertion !== undefined) generatedAssertions.push(positive.assertion);
      else if (positive.finding !== undefined) findings.push(positive.finding);

      // Negative/boundary/adversarial variants require both a positive
      // expected_text to invert against (otherwise there is nothing
      // authoritative to assert "absent") and at least one editable field
      // to perturb — a pure navigation/click criterion has no input to
      // vary (SPEC-207 §3's "normal, alternate, boundary, and failure
      // behavior" applies per input, not per click).
      if (expectedText === undefined || editableFields.length === 0) continue;

      for (const field of editableFields) {
        for (const variant of ["negative", "boundary", "adversarial"] as const) {
          const built = this.#buildCase({
            request,
            criterionId,
            variant,
            matchedFields,
            matchedAction,
            fieldValues: new Map([[field.id, variantValue(variant)]]),
            expectedText,
            variantField: field,
          });
          testCases.push(built.testCase);
          if (built.assertion !== undefined) generatedAssertions.push(built.assertion);
        }
      }
    }

    return {
      ok: true,
      value: {
        schema_version: "1.0.0",
        workspace_id: request.workspace_id,
        requirement_ref: request.requirement_ref,
        test_cases: testCases,
        findings,
        generated_assertions: generatedAssertions,
      },
    };
  }

  #buildCase(input: Readonly<{
    request: TestCaseGenerationRequest;
    criterionId: string;
    variant: TestCaseVariant;
    matchedFields: readonly TestCaseGenerationUiElement[];
    matchedAction: TestCaseGenerationUiElement | undefined;
    fieldValues: ReadonlyMap<string, string> | undefined;
    expectedText: string | undefined;
    variantField: TestCaseGenerationUiElement | undefined;
  }>): Readonly<{ testCase: TestCase; assertion: TestCaseGeneratedAssertion | undefined; finding: TestCaseGenerationFinding | undefined }> {
    const { request, criterionId, variant, matchedFields, matchedAction, fieldValues, expectedText, variantField } = input;
    const testCaseId = this.#dependencies.ids.next("test-case");

    const steps: TestCaseStep[] = [{ action: "navigate", input: { url: request.ui_map_source_url } }];
    for (const field of matchedFields) {
      const value = fieldValues?.get(field.id);
      steps.push({
        action: "type",
        input: {
          accessible_name: field.accessible_name ?? "",
          accessible_role: field.accessible_role ?? "",
          ...(value !== undefined ? { value } : {}),
        },
      });
    }
    if (matchedAction !== undefined) {
      steps.push({
        action: "click",
        input: { accessible_name: matchedAction.accessible_name ?? "", accessible_role: matchedAction.accessible_role ?? "" },
      });
    }

    let assertionText: string;
    let assertion: TestCaseGeneratedAssertion | undefined;
    let finding: TestCaseGenerationFinding | undefined;

    if (variant === "positive") {
      if (expectedText !== undefined) {
        assertionText = `After the step sequence, the page contains the text "${expectedText}".`;
        assertion = { test_case_id: testCaseId, expected_text: expectedText };
      } else {
        assertionText =
          matchedAction !== undefined
            ? `The "${matchedAction.accessible_name}" action completes without a governed failure outcome.`
            : `The discovered field(s) accept the input required by "${criterionId}".`;
        finding = {
          id: this.#dependencies.ids.next("finding"),
          category: "missing_expected_result",
          message: `Acceptance criterion "${criterionId}" has no expected_text field, so no executable assertion was generated for test case "${testCaseId}" — it cannot run unattended until one is supplied or a human authors a plan.`,
          evidence: [`${request.requirement_ref}#${criterionId}`, `test-case:${testCaseId}`],
        };
      }
    } else {
      // expectedText is guaranteed defined here (caller only builds these
      // variants when it is).
      const forbidden =
        variant === "negative"
          ? [expectedText as string]
          : variant === "boundary"
            ? [...SYSTEM_ERROR_MARKERS]
            : [...ADVERSARIAL_VALUES, ...SYSTEM_ERROR_MARKERS];
      assertionText =
        variant === "negative"
          ? `Submitting an invalid "${variantField?.accessible_name}" value does NOT produce the text "${expectedText}".`
          : variant === "boundary"
            ? `Submitting an oversized "${variantField?.accessible_name}" value produces no leaked system-error text.`
            : `Submitting an injection/XSS probe into "${variantField?.accessible_name}" is not reflected unescaped, does not execute (no dialog fires), and produces no leaked system-error text.`;
      assertion = {
        test_case_id: testCaseId,
        forbidden_text: forbidden,
        ...(variant === "adversarial" ? { expect_no_dialog: true } : {}),
      };
    }

    const expectedResults: TestCaseExpectedResult[] = [
      { assertion: assertionText, authority: `${request.requirement_ref}#${criterionId}` },
    ];

    const testCase: TestCase = {
      id: testCaseId,
      version: "1.0.0",
      status: "draft",
      purpose:
        variant === "positive"
          ? `Validate acceptance criterion "${criterionId}" of ${request.requirement_title}.`
          : `Validate acceptance criterion "${criterionId}" of ${request.requirement_title} under a ${variant} input on "${variantField?.accessible_name}".`,
      traceability: [request.requirement_ref, `${request.requirement_ref}#${criterionId}`],
      preconditions: [`Semantic UI Map available for ${request.ui_map_source_url}`],
      workspace_scope: request.workspace_id,
      steps,
      expected_results: expectedResults,
      owner: "test-design-generator",
      priority: variant === "positive" ? "medium" : "high",
      tags: ["generated", "tracer-bullet", variant],
    };

    return { testCase, assertion, finding };
  }
}

function variantValue(variant: "negative" | "boundary" | "adversarial"): string {
  if (variant === "boundary") return BOUNDARY_VALUE;
  if (variant === "adversarial") return ADVERSARIAL_VALUES[0]!;
  return "wrong-value";
}

/**
 * Word-boundary match, not raw substring — a field named "Password" must
 * not spuriously bind a statement containing "Passwordless" (or any other
 * superstring). Uses alphanumeric lookaround rather than `\b` because `\b`
 * only fires at a word/non-word transition: an accessible name ending in a
 * non-word character (e.g. "Save (draft)") has no such transition at its
 * own boundary, so `\b` would silently fail to match there.
 * `accessibleName` is escaped before use in the RegExp since it's
 * arbitrary UI text, not a pattern.
 */
function statementMentionsName(statement: string, accessibleName: string | undefined): boolean {
  if (accessibleName === undefined || accessibleName.trim().length === 0) return false;
  const escaped = accessibleName.trim().replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`(?<![A-Za-z0-9_])${escaped}(?![A-Za-z0-9_])`, "i").test(statement);
}
